# Generated by Django 5.2.15 on 2026-07-31 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrainSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allowed_discrepancy_percent",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "sensor_warning_percent",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Настройки зерна",
            },
        ),
        migrations.CreateModel(
            name="Silo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("total_capacity_kg", models.PositiveBigIntegerField()),
                (
                    "grain_culture",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "grain_class",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("allow_mixing", models.BooleanField(default=False)),
                ("is_quarantine", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "unloading_line",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "sensor_estimated_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="GrainSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=200)),
                ("contract", models.CharField(blank=True, default="", max_length=200)),
                ("culture", models.CharField(max_length=100)),
                (
                    "grain_class",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("expected_date", models.DateField(blank=True, null=True)),
                (
                    "expected_total_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "document_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("wagons_expected", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grain_supplies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Wagon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, default="", max_length=30)),
                ("status", models.CharField(default="expected", max_length=30)),
                ("unplanned", models.BooleanField(default=False)),
                (
                    "document_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "expected_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gross_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "tare_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "net_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "unloading_point",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("unloading_started_at", models.DateTimeField(blank=True, null=True)),
                ("unloading_finished_at", models.DateTimeField(blank=True, null=True)),
                ("unloading_paused", models.BooleanField(default=False)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("exit_note", models.CharField(blank=True, default="", max_length=300)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arrived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_silo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_wagons",
                        to="grain.silo",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wagons",
                        to="grain.grainsupply",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SiloReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_kg", models.PositiveBigIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "silo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="grain.silo",
                    ),
                ),
                (
                    "wagon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="grain.wagon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiloAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_kg", models.PositiveBigIntegerField()),
                (
                    "measurement_source",
                    models.CharField(default="manual", max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "silo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="grain.silo",
                    ),
                ),
                (
                    "wagon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="grain.wagon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moisture",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impurity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "grain_class",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("infestation", models.BooleanField(default=False)),
                ("damage", models.CharField(blank=True, default="", max_length=300)),
                ("note", models.TextField(blank=True, default="")),
                ("decision", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wagon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_checks",
                        to="grain.wagon",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GrainMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_type", models.CharField(max_length=25)),
                ("delta_kg", models.BigIntegerField()),
                ("balance_after_kg", models.BigIntegerField()),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="grain.grainsupply",
                    ),
                ),
                (
                    "silo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="grain.silo",
                    ),
                ),
                (
                    "wagon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="grain.wagon",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WeighingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("weight_kg", models.PositiveBigIntegerField()),
                (
                    "scale_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("source", models.CharField(default="manual", max_length=10)),
                (
                    "manual_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "previous_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wagon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighings",
                        to="grain.wagon",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="wagon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "expected",
                            "arrived",
                            "gross_weighed",
                            "lab_pending",
                            "unloading_allowed",
                            "silo_assigned",
                            "unloading",
                            "unloading_completed",
                            "tare_weighed",
                            "inventoried",
                            "exit_allowed",
                            "exited",
                            "completed",
                            "unplanned",
                            "waiting_for_approval",
                            "rejected",
                            "quarantine",
                            "insufficient_capacity",
                            "weight_discrepancy",
                            "reweighing_required",
                            "blocked",
                            "return_to_supplier",
                            "cancelled",
                        ],
                    )
                ),
                name="wagon_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="grainmovement",
            index=models.Index(fields=["silo", "-id"], name="grainmove_silo_idx"),
        ),
    ]
