# Generated by Django 5.2.15 on 2026-07-31 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiloType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "grain_culture",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "grain_class",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("color", models.CharField(default="#C58A35", max_length=7)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_silo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_types",
                        to="grain.silo",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="silo",
            name="silo_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="silos",
                to="grain.silotype",
            ),
        ),
    ]
