# Generated by Django 5.2.15 on 2026-07-31 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_grain_types(apps, schema_editor):
    GrainSupply = apps.get_model("grain", "GrainSupply")
    Silo = apps.get_model("grain", "Silo")
    SiloType = apps.get_model("grain", "SiloType")

    def resolve(culture, grain_class):
        culture = (culture or "").strip()
        grain_class = (grain_class or "").strip()
        existing = SiloType.objects.filter(
            grain_culture=culture, grain_class=grain_class
        ).first()
        if existing:
            return existing
        label = culture or "Тип зерна"
        if grain_class:
            label = f"{label} · {grain_class} класс"
        candidate = label
        suffix = 2
        while SiloType.objects.filter(name=candidate).exists():
            candidate = f"{label} ({suffix})"
            suffix += 1
        return SiloType.objects.create(
            name=candidate,
            grain_culture=culture,
            grain_class=grain_class,
        )

    for silo in Silo.objects.filter(silo_type__isnull=True):
        if silo.grain_culture or silo.grain_class:
            silo.silo_type = resolve(silo.grain_culture, silo.grain_class)
            silo.save(update_fields=["silo_type"])

    for supply in GrainSupply.objects.filter(grain_type__isnull=True):
        supply.grain_type = resolve(supply.culture, supply.grain_class)
        supply.save(update_fields=["grain_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("grain", "0002_silotype_silo_silo_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wagon",
            name="wagon_status_valid",
        ),
        migrations.AddField(
            model_name="grainsupply",
            name="assigned_silo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planned_supplies",
                to="grain.silo",
            ),
        ),
        migrations.AddField(
            model_name="grainsupply",
            name="grain_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplies",
                to="grain.silotype",
            ),
        ),
        migrations.RunPython(populate_grain_types, migrations.RunPython.noop),
        migrations.AddField(
            model_name="grainsupply",
            name="simple_flow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wagon",
            name="number_camera_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="wagon",
            name="number_source",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="wagon",
            name="silo_arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wagon",
            name="workflow",
            field=models.CharField(default="legacy", max_length=20),
        ),
        migrations.AddConstraint(
            model_name="wagon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "expected",
                            "arrived",
                            "at_silo",
                            "gross_weighed",
                            "lab_pending",
                            "unloading_allowed",
                            "silo_assigned",
                            "unloading",
                            "unloading_completed",
                            "tare_weighed",
                            "inventoried",
                            "exit_allowed",
                            "exited",
                            "completed",
                            "unplanned",
                            "waiting_for_approval",
                            "rejected",
                            "quarantine",
                            "insufficient_capacity",
                            "weight_discrepancy",
                            "reweighing_required",
                            "blocked",
                            "return_to_supplier",
                            "cancelled",
                        ],
                    )
                ),
                name="wagon_status_valid",
            ),
        ),
    ]
