# Generated by Django 5.2.16 on 2026-08-03 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0003_remove_wagon_wagon_status_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wagon",
            name="cargo_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wagon",
            name="direction",
            field=models.CharField(default="intake", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="wagon",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["intake", "passage"])),
                name="wagon_direction_valid",
            ),
        ),
    ]
