# Generated by Django 5.2.15 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0021_vehicle_plate_events"),
        ("grain", "0004_wagon_cargo_name_wagon_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagon",
            name="vehicle_plate_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grain_wagon",
                to="cameras.vehicleplateevent",
            ),
        ),
    ]
