# Generated by Django 5.2.15 on 2026-08-26

import re
import django.db.models.deletion
from django.db import migrations, models


ACTIVE_PASSAGE_STATUSES = (
    "arrived",
    "at_silo",
    "blocked",
    "exit_allowed",
    "gross_weighed",
    "insufficient_capacity",
    "inventoried",
    "lab_pending",
    "quarantine",
    "rejected",
    "reweighing_required",
    "silo_assigned",
    "tare_weighed",
    "unloading",
    "unloading_allowed",
    "unloading_completed",
    "waiting_for_approval",
    "weight_discrepancy",
)

KZ_PLATE_RE = re.compile(r"^[0-9]{3}[A-Z]{3}[0-9]{2}$")


def canonicalize_active_passage_numbers(apps, schema_editor):
    wagon_model = apps.get_model("grain", "Wagon")
    database = schema_editor.connection.alias
    rows = list(
        wagon_model.objects.using(database)
        .filter(
            direction="passage",
            status__in=ACTIVE_PASSAGE_STATUSES,
        )
        .exclude(number="")
        .order_by("id")
        .values("id", "number")
    )

    seen: dict[str, int] = {}
    updates: list[tuple[int, str]] = []
    for row in rows:
        raw = row["number"]
        compact = re.sub(r"[\s-]+", "", raw.strip()).upper()
        if not raw.strip():
            canonical = ""
        else:
            canonical = compact if KZ_PLATE_RE.fullmatch(compact) else raw
        if canonical:
            previous_id = seen.get(canonical)
            if previous_id is not None:
                raise RuntimeError(
                    "Active passage plate collision after canonicalization: "
                    f"wagon ids {previous_id} and {row['id']}"
                )
            seen[canonical] = row["id"]
        if canonical != raw:
            updates.append((row["id"], canonical))

    for wagon_id, canonical in updates:
        wagon_model.objects.using(database).filter(pk=wagon_id).update(
            number=canonical
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0022_vehicle_plate_automation"),
        ("grain", "0005_wagon_vehicle_plate_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagon",
            name="exit_vehicle_plate_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grain_exit_wagon",
                to="cameras.vehicleplateevent",
            ),
        ),
        migrations.RunPython(
            canonicalize_active_passage_numbers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="wagon",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(
                        direction="passage",
                        status__in=ACTIVE_PASSAGE_STATUSES,
                    )
                    & ~models.Q(number="")
                ),
                fields=("number",),
                name="grain_one_active_passage_plate",
            ),
        ),
    ]
