# Generated by Django 5.2.15 on 2026-08-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grain", "0006_auto_export_plate_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassageWeightCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField(unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("entry", "Въезд"), ("exit", "Выезд")],
                        max_length=10,
                    ),
                ),
                ("wagon_status_before", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="processing",
                        max_length=12,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("claimed", "Запрос принят"),
                            ("recognizing", "Распознавание номера"),
                            ("applying", "Сохранение результата"),
                            ("done", "Завершено"),
                        ],
                        default="claimed",
                        max_length=16,
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                (
                    "camera_source",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("stable_weight_at", models.DateTimeField(blank=True, null=True)),
                ("weight_kg", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "scale_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "scale_age_seconds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "scale_updated_at",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("recognized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_votes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "detector_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("ai_payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("retryable", models.BooleanField(default=False)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "error_detail",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wagon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passage_weight_captures",
                        to="grain.wagon",
                    ),
                ),
                (
                    "wagon_id_snapshot",
                    models.PositiveBigIntegerField(db_index=True),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("action__in", ["entry", "exit"])),
                        name="grain_passage_capture_action_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["processing", "completed", "failed"])
                        ),
                        name="grain_passage_capture_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "stage__in",
                                ["claimed", "recognizing", "applying", "done"],
                            )
                        ),
                        name="grain_passage_capture_stage_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["processing", "completed"])
                        ),
                        fields=("wagon", "action"),
                        name="grain_one_active_passage_capture",
                    ),
                ],
            },
        ),
    ]
