# Generated by Django 5.2.15 on 2026-09-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_truck_lane_state(apps, _schema_editor):
    state = apps.get_model("grain", "PassageScaleAutomationState")
    state.objects.get_or_create(scale_number="truck", defaults={"phase": "unarmed"})


def remove_truck_lane_state(apps, _schema_editor):
    state = apps.get_model("grain", "PassageScaleAutomationState")
    state.objects.filter(scale_number="truck").delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cameras", "0022_vehicle_plate_automation"),
        ("grain", "0007_vehicle_plate_weight_first"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomaticPassageCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField(unique=True)),
                ("scale_number", models.CharField(default="truck", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Нужен оператор"),
                        ],
                        default="processing",
                        max_length=12,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("claimed", "Весы захвачены"),
                            ("recognizing", "Распознавание номера"),
                            ("applying", "Сохранение рейса"),
                            ("done", "Завершено"),
                        ],
                        default="claimed",
                        max_length=16,
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                (
                    "camera_source",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("stable_weight_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("weight_kg", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "scale_age_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "scale_updated_at",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("recognized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_votes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "detector_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=7, null=True
                    ),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=7, null=True
                    ),
                ),
                ("ai_payload_json", models.JSONField(blank=True, default=dict)),
                ("recognition_attempts", models.PositiveSmallIntegerField(default=0)),
                ("final_lookup_attempted", models.BooleanField(default=False)),
                ("retryable", models.BooleanField(default=False)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_detail",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("action", models.CharField(blank=True, default="", max_length=10)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_plate_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automatic_passage_capture",
                        to="cameras.vehicleplateevent",
                    ),
                ),
                (
                    "wagon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automatic_passage_captures",
                        to="grain.wagon",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=["processing", "completed", "failed"]
                        ),
                        name="grain_auto_capture_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            stage__in=["claimed", "recognizing", "applying", "done"]
                        ),
                        name="grain_auto_capture_stage_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(action__in=["", "entry", "exit"]),
                        name="grain_auto_capture_action_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PassageScaleAutomationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scale_number",
                    models.CharField(default="truck", max_length=50, unique=True),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("unarmed", "Ожидает подтверждения пустых весов"),
                            ("armed", "Ожидает машину"),
                            ("stabilizing", "Подтверждает стабильный вес"),
                            ("processing", "Обрабатывает взвешивание"),
                            ("awaiting_clear", "Ожидает освобождения весов"),
                        ],
                        default="unarmed",
                        max_length=20,
                    ),
                ),
                ("clear_streak", models.PositiveSmallIntegerField(default=0)),
                ("stable_streak", models.PositiveSmallIntegerField(default=0)),
                (
                    "candidate_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_capture",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lane_state",
                        to="grain.automaticpassagecapture",
                    ),
                ),
            ],
            options={
                "ordering": ["scale_number"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            phase__in=[
                                "unarmed",
                                "armed",
                                "stabilizing",
                                "processing",
                                "awaiting_clear",
                            ]
                        ),
                        name="grain_passage_scale_phase_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_truck_lane_state,
            remove_truck_lane_state,
        ),
    ]
