# Generated by Django 5.2.15 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grain", "0008_automatic_passage_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="passagescaleautomationstate",
            name="stability_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passagescaleautomationstate",
            name="stable_weight_seconds",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name="passagescaleautomationstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    stable_weight_seconds__gte=2,
                    stable_weight_seconds__lte=60,
                ),
                name="grain_passage_scale_stable_seconds_valid",
            ),
        ),
    ]
