# Generated by Django 5.2.15 on 2026-09-04 10:28

import apps.grain.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0030_multi_warehouse_stock_guard"),
        ("grain", "0009_passage_scale_stable_weight_seconds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnassignedWeighing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.PositiveBigIntegerField()),
                ("stable_weight_at", models.DateTimeField()),
                (
                    "scale_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "scale_age_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "scale_updated_at",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("camera", models.CharField(blank=True, default="", max_length=32)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.grain.models.unassigned_weighing_photo_path,
                    ),
                ),
                (
                    "photo_request_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ожидает"),
                            ("assigned", "Привязано"),
                            ("discarded", "Отклонено"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("action", models.CharField(blank=True, default="", max_length=10)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="automaticpassagecapture",
            name="grain_auto_capture_action_valid",
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="attempt_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="attempt_stable_weight_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="needs_new_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="plate_unresolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="requires_acknowledgement",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="weighingrecord",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.grain.models.weighing_photo_path
            ),
        ),
        migrations.AddField(
            model_name="weighingrecord",
            name="photo_camera",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="weighingrecord",
            name="photo_request_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="automaticpassagecapture",
            constraint=models.CheckConstraint(
                condition=models.Q(("action__in", ["", "entry", "exit", "unassigned"])),
                name="grain_auto_capture_action_valid",
            ),
        ),
        migrations.AddField(
            model_name="unassignedweighing",
            name="capture",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unassigned_weighing",
                to="grain.automaticpassagecapture",
            ),
        ),
        migrations.AddField(
            model_name="unassignedweighing",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unassignedweighing",
            name="wagon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unassigned_weighings",
                to="grain.wagon",
            ),
        ),
        migrations.AddConstraint(
            model_name="unassignedweighing",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "assigned", "discarded"])),
                name="grain_unassigned_weighing_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unassignedweighing",
            constraint=models.CheckConstraint(
                condition=models.Q(("action__in", ["", "entry", "exit"])),
                name="grain_unassigned_weighing_action_valid",
            ),
        ),
    ]
