# Generated by Django 5.2.15 on 2026-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0010_weighing_photos_and_unattended_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не определена"),
                    ("front", "Передом к камере"),
                    ("rear", "Задом к камере"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="orientation_confidence",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="unassignedweighing",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не определена"),
                    ("front", "Передом к камере"),
                    ("rear", "Задом к камере"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="unassignedweighing",
            name="vehicle_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="weighingrecord",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не определена"),
                    ("front", "Передом к камере"),
                    ("rear", "Задом к камере"),
                ],
                default="",
                max_length=8,
            ),
        ),
    ]
