# Generated by Django 5.2.15 on 2026-09-05 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0011_vehicle_orientation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleOrientationSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_kind",
                    models.CharField(
                        choices=[
                            ("weighing", "Взвешивание"),
                            ("unassigned", "Неопознанное взвешивание"),
                        ],
                        max_length=12,
                    ),
                ),
                ("record_id", models.PositiveBigIntegerField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("front", "Передом к камере"),
                            ("rear", "Задом к камере"),
                        ],
                        max_length=8,
                    ),
                ),
                ("label_source", models.CharField(max_length=8)),
                ("weight_kg", models.PositiveBigIntegerField()),
                ("captured_at", models.DateTimeField()),
                (
                    "model_orientation",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("conflict", models.BooleanField(default=False)),
                ("excluded", models.BooleanField(default=False)),
                ("removal_pending", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record_kind", "record_id"),
                        name="grain_one_orientation_sample_per_record",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("label__in", ["front", "rear"])),
                        name="grain_orientation_sample_label_valid",
                    ),
                ],
            },
        ),
    ]
