# Generated by Django 5.2.17 on 2026-09-08 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0013_vehicle_orientation_dataset_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="recognition_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="departure_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automaticpassagecapture",
            name="recognition_dispatched",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="WeighingPhotoDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("camera", models.CharField(max_length=32)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="grain/evidence/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Фото ожидается"),
                            ("retrying", "Повторная загрузка"),
                            ("saved", "Фото сохранено"),
                            ("unavailable", "Фото недоступно"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("snapshot_attempted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_deliveries",
                        to="grain.automaticpassagecapture",
                    ),
                ),
            ],
        ),
    ]
