# Generated by Django 5.2.17 on 2026-09-08 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0015_queue_missing_weighing_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeighingIdentityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=16),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "response_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=100)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weighing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_check",
                        to="grain.unassignedweighing",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending",
                                    "processing",
                                    "retrying",
                                    "review",
                                    "matched",
                                ],
                            )
                        ),
                        name="grain_identity_status_valid",
                    )
                ],
            },
        ),
    ]
