# Generated by Django 5.2.17 on 2026-09-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0016_weighing_identity_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="weighingrecord",
            name="reference_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tare_reuses",
                to="grain.weighingrecord",
            ),
        ),
    ]
