# Generated by Django 5.2.17 on 2026-09-09 07:35

import re

import django.db.models.deletion
from django.db import migrations, models


def seed_latest_measured_tares(apps, schema_editor):
    Record = apps.get_model("grain", "WeighingRecord")
    Memory = apps.get_model("grain", "VehicleTareMemory")
    alias = schema_editor.connection.alias
    latest = {}
    for record in Record.objects.using(alias).filter(
        wagon__direction="passage", kind="gross", source="scale",
        orientation="front", reference_record__isnull=True,
    ).select_related("wagon").order_by("created_at", "pk").iterator():
        number = re.sub(r"[\s-]+", "", record.wagon.number.upper())
        if re.fullmatch(r"(?:[0-9]{3}[A-Z]{2,3}[0-9]{2}|[A-Z][0-9]{3}[A-Z]{3})", number):
            latest[number] = Memory(number=number, record_id=record.pk, observed_at=record.created_at)
    Memory.objects.using(alias).bulk_create(list(latest.values()), batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0017_weighing_tare_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTareMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_tare_memories",
                        to="grain.weighingrecord",
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_latest_measured_tares, migrations.RunPython.noop),
    ]
