# Generated by Django 5.2.17 on 2026-09-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0019_confirmed_entry_tare_memory"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagonArchStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.UUIDField(unique=True)),
                ("camera", models.CharField(max_length=32)),
                ("arrived_at", models.DateTimeField(db_index=True)),
                ("full_weight_kg", models.PositiveBigIntegerField()),
                (
                    "scale_age_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "scale_updated_at",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "still_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                ("number", models.CharField(blank=True, default="", max_length=30)),
                (
                    "number_source",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "recognition_error",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("ocr_attempts", models.PositiveSmallIntegerField(default=0)),
                ("photo_request_id", models.UUIDField(db_index=True)),
                ("opened_wagon_id", models.BigIntegerField(blank=True, null=True)),
                ("entry_applied_at", models.DateTimeField(blank=True, null=True)),
                ("departure_id", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "exit_weight_kg",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("exit_stable_at", models.DateTimeField(blank=True, null=True)),
                ("departed_at", models.DateTimeField(blank=True, null=True)),
                ("motion_gap", models.BooleanField(default=False)),
                ("exit_applied_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="open", max_length=12)),
                (
                    "blocked_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "blocked_detail",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wagon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arch_stops",
                        to="grain.wagon",
                    ),
                ),
                (
                    "continues",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continued_by",
                        to="grain.wagonarchstop",
                    ),
                ),
            ],
            options={
                "ordering": ["-arrived_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["open", "closed", "attention", "superseded"],
                            )
                        ),
                        name="wagon_arch_stop_status_valid",
                    )
                ],
            },
        ),
    ]
