# Generated by Django 5.2.17 on 2026-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0020_wagon_arch_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagon",
            name="workflow",
            field=models.CharField(default="simple", max_length=20),
        ),
    ]
