# Generated by Django 5.2.17 on 2026-09-30 06:47

import apps.grain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grain", "0023_legacy_identity_review_reasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagon",
            name="arrival_photo",
            field=models.FileField(
                blank=True,
                db_default="",
                default="",
                upload_to=apps.grain.models.wagon_arrival_photo_path,
            ),
        ),
        migrations.AddField(
            model_name="wagon",
            name="arrival_photo_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
