# Generated by Django 5.2.15 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="arrival_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
