[mypy]
python_version = 3.12
files = apps, config, healthcheck.py, manage.py
exclude = (^|/)(tests|migrations)/
disable_error_code = import-untyped
check_untyped_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
strict_equality = True
extra_checks = True
show_error_codes = True
pretty = False
