[mypy]
python_version = 3.12
files = apps, config, healthcheck.py, heartbeat_healthcheck.py, apipay_monitor_healthcheck.py, celery_beat_healthcheck.py, passage_scale_monitor_healthcheck.py, shipping_transport_monitor_healthcheck.py, whatsapp_bot_healthcheck.py, manage.py
exclude = (^|/)(tests|migrations)/
disable_error_code = import-untyped
check_untyped_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
strict_equality = True
extra_checks = True
show_error_codes = True
pretty = False
