# Generated by Django 5.2.15 on 2026-07-28 08:55
"""Индекс входящих уведомлений клиента: непрочитанные сверху.

CONCURRENTLY, чтобы не блокировать запись в растущую таблицу.
"""

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("clients", "0013_client_last_name_optional"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="notification",
            index=models.Index(
                fields=["client", "is_read", "-created_at"],
                name="notification_inbox_idx",
            ),
        ),
    ]
