# Generated by Django 5.2.15 on 2026-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_stockitem_bags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="balance_after",
            field=models.IntegerField(),
        ),
    ]
