# Generated by Django 5.2.15 on 2026-06-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_stockmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="bags",
            field=models.IntegerField(default=0),
        ),
    ]
