# Generated by Django 5.2.15 on 2026-07-28 08:55
"""Индекс истории движений склада: читается «сверху».

CONCURRENTLY, чтобы не блокировать запись в растущую таблицу.
"""

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("catalog", "0011_expand_product_weights"),
        ("warehouse", "0004_alter_stockmovement_balance_after"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="stockmovement",
            index=models.Index(
                fields=["-created_at", "-id"], name="stockmovement_recent_idx"
            ),
        ),
    ]
