# Generated by Django 5.2.15 on 2026-08-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_factorymap"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FactoryMap",
        ),
    ]
