# Generated by Django 5.2.15 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0007_delete_factorymap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("adjustment", "Корректировка"),
                    ("shipment", "Отгрузка"),
                    ("shipment_correction", "Корректировка отгрузки"),
                    ("receipt", "Приёмка"),
                ],
                default="adjustment",
                max_length=20,
            ),
        ),
    ]
