# Generated by Django 5.2.15 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q

DEFAULT_WAREHOUSE_CODE = "main"
DEFAULT_WAREHOUSE_NAME = "Основной склад"


def create_default_warehouse_and_backfill(apps, schema_editor):
    Warehouse = apps.get_model("warehouse", "Warehouse")
    StockItem = apps.get_model("warehouse", "StockItem")
    StockReceipt = apps.get_model("warehouse", "StockReceipt")
    StockMovement = apps.get_model("warehouse", "StockMovement")

    warehouse, _created = Warehouse.objects.get_or_create(
        code=DEFAULT_WAREHOUSE_CODE,
        defaults={
            "name": DEFAULT_WAREHOUSE_NAME,
            "address": "",
            "is_active": True,
            "is_default": True,
        },
    )
    update_fields = []
    if warehouse.name != DEFAULT_WAREHOUSE_NAME:
        warehouse.name = DEFAULT_WAREHOUSE_NAME
        update_fields.append("name")
    if not warehouse.is_active:
        warehouse.is_active = True
        update_fields.append("is_active")
    if not warehouse.is_default:
        Warehouse.objects.filter(is_default=True).exclude(pk=warehouse.pk).update(
            is_default=False
        )
        warehouse.is_default = True
        update_fields.append("is_default")
    if update_fields:
        warehouse.save(update_fields=update_fields)

    for model in (StockItem, StockReceipt, StockMovement):
        model.objects.filter(warehouse_id__isnull=True).update(
            warehouse_id=warehouse.pk
        )


def clear_warehouse_assignments(apps, schema_editor):
    for model_name in ("StockItem", "StockReceipt", "StockMovement"):
        model = apps.get_model("warehouse", model_name)
        model.objects.update(warehouse_id=None)


def install_legacy_write_guards(apps, schema_editor):
    """Keep writes from the rollback image warehouse-correct on PostgreSQL."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION public.asyl_main_wh_id()
        RETURNS bigint
        LANGUAGE plpgsql
        STABLE
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            result bigint;
        BEGIN
            SELECT id INTO result
            FROM public.warehouse_warehouse
            WHERE code = 'main';
            IF result IS NULL THEN
                RAISE EXCEPTION 'compatibility warehouse main is not configured'
                    USING ERRCODE = '23514';
            END IF;
            RETURN result;
        END;
        $$;

        CREATE OR REPLACE FUNCTION public.asyl_product_wh_id(product_pk bigint)
        RETURNS bigint
        LANGUAGE plpgsql
        STABLE
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            result bigint;
        BEGIN
            SELECT warehouse_id INTO result
            FROM public.warehouse_stockitem
            WHERE product_id = product_pk;
            RETURN COALESCE(result, public.asyl_main_wh_id());
        END;
        $$;

        CREATE OR REPLACE FUNCTION public.wh_compat_stockitem_warehouse()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
            IF TG_OP = 'UPDATE'
               AND OLD.warehouse_id IS NOT NULL
               AND NEW.warehouse_id IS DISTINCT FROM OLD.warehouse_id THEN
                RAISE EXCEPTION 'stock item warehouse cannot be changed'
                    USING ERRCODE = '23514';
            END IF;
            NEW.warehouse_id := COALESCE(
                NEW.warehouse_id,
                public.asyl_main_wh_id()
            );
            RETURN NEW;
        END;
        $$;

        DROP TRIGGER IF EXISTS wh_compat_stockitem_warehouse_bi
            ON public.warehouse_stockitem;
        CREATE TRIGGER wh_compat_stockitem_warehouse_bi
        BEFORE INSERT OR UPDATE OF warehouse_id ON public.warehouse_stockitem
        FOR EACH ROW EXECUTE FUNCTION public.wh_compat_stockitem_warehouse();

        CREATE OR REPLACE FUNCTION public.wh_compat_protect_stockitem_delete()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
            -- Keep Product's existing hard-delete contract working. Django's
            -- collector supplies the exact parent id through a transaction-
            -- local marker while it removes dependent rows before the parent.
            IF current_setting(
                    'asyl.deleting_product_id',
                    TRUE
               ) = OLD.product_id::text
            THEN
                RETURN OLD;
            END IF;
            RAISE EXCEPTION
                'stock assignment cannot be deleted during rollout'
                USING ERRCODE = '23514';
        END;
        $$;

        DROP TRIGGER IF EXISTS wh_compat_stockitem_delete_bd
            ON public.warehouse_stockitem;
        CREATE TRIGGER wh_compat_stockitem_delete_bd
        BEFORE DELETE ON public.warehouse_stockitem
        FOR EACH ROW EXECUTE FUNCTION public.wh_compat_protect_stockitem_delete();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION public.wh_compat_product_event_warehouse()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            expected_warehouse bigint;
        BEGIN
            expected_warehouse := public.asyl_product_wh_id(NEW.product_id);
            IF NEW.warehouse_id IS NULL THEN
                NEW.warehouse_id := expected_warehouse;
            ELSIF NEW.warehouse_id <> expected_warehouse THEN
                RAISE EXCEPTION
                    'product %% belongs to warehouse %%, not %%',
                    NEW.product_id, expected_warehouse, NEW.warehouse_id
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$;

        DROP TRIGGER IF EXISTS wh_compat_receipt_warehouse_bi
            ON public.warehouse_stockreceipt;
        CREATE TRIGGER wh_compat_receipt_warehouse_bi
        BEFORE INSERT OR UPDATE OF product_id, warehouse_id
            ON public.warehouse_stockreceipt
        FOR EACH ROW EXECUTE FUNCTION public.wh_compat_product_event_warehouse();

        DROP TRIGGER IF EXISTS wh_compat_movement_warehouse_bi
            ON public.warehouse_stockmovement;
        CREATE TRIGGER wh_compat_movement_warehouse_bi
        BEFORE INSERT OR UPDATE OF product_id, warehouse_id
            ON public.warehouse_stockmovement
        FOR EACH ROW EXECUTE FUNCTION public.wh_compat_product_event_warehouse();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION public.wh_protect_main_warehouse()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
            IF TG_OP = 'DELETE'
               AND (OLD.code = 'main' OR OLD.is_default IS TRUE) THEN
                RAISE EXCEPTION 'main or default warehouse cannot be deleted'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.code = 'main' THEN
                IF NEW.code IS DISTINCT FROM OLD.code THEN
                    RAISE EXCEPTION 'compatibility warehouse main code cannot change'
                        USING ERRCODE = '23514';
                END IF;
                IF NEW.is_active IS NOT TRUE THEN
                    RAISE EXCEPTION 'compatibility warehouse main must stay active'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$;

        DROP TRIGGER IF EXISTS wh_protect_main_warehouse_bud
            ON public.warehouse_warehouse;
        CREATE TRIGGER wh_protect_main_warehouse_bud
        BEFORE UPDATE OR DELETE ON public.warehouse_warehouse
        FOR EACH ROW EXECUTE FUNCTION public.wh_protect_main_warehouse();
        """
    )


def uninstall_legacy_write_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS wh_compat_stockitem_warehouse_bi
            ON public.warehouse_stockitem;
        DROP TRIGGER IF EXISTS wh_compat_stockitem_delete_bd
            ON public.warehouse_stockitem;
        DROP TRIGGER IF EXISTS wh_compat_receipt_warehouse_bi
            ON public.warehouse_stockreceipt;
        DROP TRIGGER IF EXISTS wh_compat_movement_warehouse_bi
            ON public.warehouse_stockmovement;
        DROP TRIGGER IF EXISTS wh_protect_main_warehouse_bud
            ON public.warehouse_warehouse;
        DROP FUNCTION IF EXISTS public.wh_compat_stockitem_warehouse();
        DROP FUNCTION IF EXISTS public.wh_compat_protect_stockitem_delete();
        DROP FUNCTION IF EXISTS public.wh_compat_product_event_warehouse();
        DROP FUNCTION IF EXISTS public.wh_protect_main_warehouse();
        DROP FUNCTION IF EXISTS public.asyl_product_wh_id(bigint);
        DROP FUNCTION IF EXISTS public.asyl_main_wh_id();
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0008_alter_stockmovement_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(is_default=True),
                        fields=("is_default",),
                        name="warehouse_one_default",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="stockitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_items",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="warehouse.warehouse",
            ),
        ),
        migrations.RunPython(
            create_default_warehouse_and_backfill,
            clear_warehouse_assignments,
        ),
        # Add a named global constraint before dropping OneToOneField's implicit
        # unique constraint.  The previous image can therefore roll back and
        # continue relying on one row per product for this whole release.
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                fields=("product",),
                name="wh_stock_product_uniq_compat",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="catalog.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "product"),
                name="wh_stock_wh_product_uniq",
            ),
        ),
        migrations.RunPython(
            install_legacy_write_guards,
            uninstall_legacy_write_guards,
        ),
    ]
