# Generated by Django 5.2.15 on 2026-09-03 03:01

import django.db.models.functions.text
from django.db import migrations, models


def normalize_and_validate_warehouse_names(apps, schema_editor):
    Warehouse = apps.get_model("warehouse", "Warehouse")
    for warehouse in Warehouse.objects.all().only("pk", "name"):
        normalized = warehouse.name.strip()
        if not normalized:
            raise RuntimeError(
                f"Warehouse #{warehouse.pk} has an empty display name"
            )
        if normalized != warehouse.name:
            Warehouse.objects.filter(pk=warehouse.pk).update(name=normalized)

    seen = set()
    duplicates = set()
    for name in Warehouse.objects.values_list("name", flat=True):
        normalized = name.casefold()
        if normalized in seen:
            duplicates.add(normalized)
        seen.add(normalized)
    if duplicates:
        raise RuntimeError(
            "Warehouse names must be unique ignoring case; duplicates: "
            + ", ".join(sorted(duplicates))
        )


def install_multi_warehouse_write_guards(apps, schema_editor):
    """Make legacy implicit writes fail closed once a product has >1 owner."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION public.asyl_product_wh_id(product_pk bigint)
        RETURNS bigint
        LANGUAGE plpgsql
        STABLE
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            result bigint;
            owner_count bigint;
            main_warehouse bigint;
        BEGIN
            main_warehouse := public.asyl_main_wh_id();
            SELECT
                COUNT(DISTINCT COALESCE(warehouse_id, main_warehouse)),
                MIN(COALESCE(warehouse_id, main_warehouse))
            INTO owner_count, result
            FROM public.warehouse_stockitem
            WHERE product_id = product_pk;

            IF owner_count = 0 THEN
                RETURN main_warehouse;
            ELSIF owner_count > 1 THEN
                RAISE EXCEPTION
                    'ambiguous warehouse for product %%',
                    product_pk
                    USING ERRCODE = '23514';
            END IF;
            RETURN result;
        END;
        $$;

        CREATE OR REPLACE FUNCTION public.wh_compat_product_event_warehouse()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            expected_warehouse bigint;
        BEGIN
            expected_warehouse := COALESCE(
                NEW.warehouse_id,
                public.asyl_product_wh_id(NEW.product_id)
            );
            IF EXISTS (
                SELECT 1
                FROM public.warehouse_stockitem
                WHERE product_id = NEW.product_id
            ) AND NOT EXISTS (
                SELECT 1
                FROM public.warehouse_stockitem
                WHERE product_id = NEW.product_id
                  AND COALESCE(
                      warehouse_id,
                      public.asyl_main_wh_id()
                  ) = expected_warehouse
            ) THEN
                RAISE EXCEPTION
                    'product %% has no stock card in warehouse %%',
                    NEW.product_id, expected_warehouse
                    USING ERRCODE = '23514';
            END IF;
            NEW.warehouse_id := expected_warehouse;
            RETURN NEW;
        END;
        $$;

        """
    )


def restore_single_warehouse_write_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION public.asyl_product_wh_id(product_pk bigint)
        RETURNS bigint
        LANGUAGE plpgsql
        STABLE
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            result bigint;
        BEGIN
            SELECT warehouse_id INTO result
            FROM public.warehouse_stockitem
            WHERE product_id = product_pk;
            RETURN COALESCE(result, public.asyl_main_wh_id());
        END;
        $$;

        CREATE OR REPLACE FUNCTION public.wh_compat_product_event_warehouse()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
            expected_warehouse bigint;
        BEGIN
            expected_warehouse := public.asyl_product_wh_id(NEW.product_id);
            IF NEW.warehouse_id IS NULL THEN
                NEW.warehouse_id := expected_warehouse;
            ELSIF NEW.warehouse_id <> expected_warehouse THEN
                RAISE EXCEPTION
                    'product %% belongs to warehouse %%, not %%',
                    NEW.product_id, expected_warehouse, NEW.warehouse_id
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_expand_product_weights"),
        ("warehouse", "0009_multi_warehouse_expand"),
    ]

    operations = [
        migrations.RunPython(
            normalize_and_validate_warehouse_names,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="stockitem",
            name="wh_stock_product_uniq_compat",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="transfer_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Связывает расходную и приходную проводки перемещения.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("adjustment", "Корректировка"),
                    ("shipment", "Отгрузка"),
                    ("shipment_correction", "Корректировка отгрузки"),
                    ("receipt", "Приёмка"),
                    ("transfer_out", "Перемещение со склада"),
                    ("transfer_in", "Перемещение на склад"),
                ],
                default="adjustment",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("warehouse__isnull", True)),
                fields=("product",),
                name="wh_stock_null_product_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                name="warehouse_name_ci_uniq",
            ),
        ),
        migrations.RunPython(
            install_multi_warehouse_write_guards,
            restore_single_warehouse_write_guards,
        ),
    ]
