# Generated by Django 5.2.17 on 2026-10-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0012_client_return_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("adjustment", "Корректировка"),
                    ("shipment", "Отгрузка"),
                    ("shipment_correction", "Корректировка отгрузки"),
                    ("receipt", "Приёмка"),
                    ("transfer_out", "Перемещение со склада"),
                    ("transfer_in", "Перемещение на склад"),
                    ("client_return", "Возврат от клиента"),
                    ("client_return_undo", "Отмена возврата от клиента"),
                ],
                default="adjustment",
                max_length=20,
            ),
        ),
    ]
