# Generated by Django 5.2.15 on 2026-06-23 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_arrival_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="debt_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="truck_number_set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="truck_numbers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(default="cash", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="confirmed", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
