# Generated by Django 5.2.15 on 2026-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_debt_requested_order_truck_number_set_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="unpaid", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="settlement_intent",
            field=models.CharField(default="debt", max_length=20),
        ),
    ]
