# Generated by Django 5.2.15 on 2026-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_statuschangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
