# Generated by Django 5.2.15 on 2026-06-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderitem_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transport_type",
            field=models.CharField(default="truck", max_length=10),
        ),
    ]
