# Generated by Django 5.2.15 on 2026-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_deleted_at_order_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="loading_camera",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
