# Generated by Django 5.2.15 on 2026-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
