# Generated by Django 5.2.15 on 2026-07-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_dynamic_department_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="accountant_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="accountant_by",
        ),
    ]
