# Generated by Django 5.2.15 on 2026-07-28 08:55
"""Индексы под чтение оплат: журнал транзакций и очередь кассы.

Индексы строятся CONCURRENTLY: таблица оплат горячая, а обычный CREATE INDEX
держит на ней блокировку записи всё время построения — на проде это означало бы
остановку кассы. Поэтому миграция неатомарна (CONCURRENTLY нельзя выполнять
внутри транзакции).
"""

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("orders", "0027_apipay_refund_checked_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="payment",
            index=models.Index(fields=["-paid_at"], name="payment_paid_at_desc_idx"),
        ),
        AddIndexConcurrently(
            model_name="payment",
            index=models.Index(fields=["status"], name="payment_status_idx"),
        ),
    ]
