# Generated by Django 5.2.17 on 2026-09-12 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_order_rejection_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payment_order_status_idx"
            ),
        ),
    ]
