# Generated by Django 5.2.17 on 2026-09-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0039_backfill_payment_status"),
        ("sales", "0003_department_apipay_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="apipaywebhookevent",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apipay_webhook_events",
                to="sales.department",
            ),
        ),
    ]
