# Generated by Django 5.2.17 on 2026-09-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_apipaywebhookevent_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiPayQrRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="issuing", max_length=32),
                ),
                ("customer_url_encrypted", models.TextField(blank=True, default="")),
                ("link_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "operation_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("operations", models.JSONField(blank=True, default=list)),
                ("execute_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refunded_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_refunds",
                        to="orders.apipayinvoice",
                    ),
                ),
                (
                    "refund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_refund",
                        to="orders.paymentrefund",
                    ),
                ),
            ],
        ),
    ]
