# Generated by Django 5.2.17 on 2026-09-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_apipay_qr_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trailer_number",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=30
            ),
        ),
    ]
