# Generated by Django 5.2.17 on 2026-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0043_backfill_truck_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rail_station",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=120
            ),
        ),
    ]
