# Generated by Django 5.2.17 on 2026-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_remove_product_ask_truck_weight"),
        ("orders", "0048_goods_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_bonus",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_bonus", False),
                    models.Q(("unit_price", 0), ("unit_price__isnull", False)),
                    _connector="OR",
                ),
                name="orderitem_bonus_is_free",
            ),
        ),
    ]
