# Generated by Django 5.2.17 on 2026-10-09 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_remove_product_ask_truck_weight"),
        ("orders", "0049_orderitem_is_bonus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreturn",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreturn",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreturn",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ждёт приёмки"),
                    ("full", "Полностью возвращено"),
                    ("partial", "Частично возвращено"),
                    ("cancelled", "Отменён"),
                ],
                db_default="full",
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="GoodsReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_label_snapshot", models.CharField(max_length=255)),
                ("bags", models.PositiveIntegerField()),
                ("paid_bags", models.PositiveIntegerField()),
                ("accepted_bags", models.PositiveIntegerField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "goods_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.goodsreturn",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("goods_return", "product"),
                        name="goods_return_item_product_once",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("bags__gt", 0)),
                        name="goods_return_item_bags_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("accepted_bags__isnull", True),
                            ("accepted_bags__lte", models.F("bags")),
                            _connector="OR",
                        ),
                        name="goods_return_item_accepted_within_bags",
                    ),
                ],
            },
        ),
    ]
