# Generated by Django 5.2.17 on 2026-10-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0052_backfill_goods_return_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrefund",
            name="goods_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="orders.goodsreturn",
            ),
        ),
    ]
