# Generated by Django 5.2.15 on 2026-06-23 04:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_bag_classes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[("Red", "Красный"), ("Green", "Зелёный"), ("Blue", "Синий")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="product",
            old_name="cv_class",
            new_name="cv_class_old",
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="new_weight_kg",
            field=models.DecimalField(
                blank=True,
                choices=[(Decimal("25"), "25 кг"), (Decimal("50"), "50 кг")],
                decimal_places=2,
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.grade",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="packaging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.packaging",
            ),
        ),
    ]
