# Generated by Django 5.2.15 on 2026-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_clientprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ask_truck_weight",
            field=models.BooleanField(default=False),
        ),
    ]
