# Generated by Django 5.2.17 on 2026-09-16 11:06

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_expand_product_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.FileField(
                blank=True,
                db_default="",
                default="",
                upload_to=apps.catalog.models.product_photo_path,
            ),
        ),
    ]
