# Generated by Django 5.2.17 on 2026-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_productalias_db_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="productalias",
            name="spelling",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
    ]
