# Generated by Django 5.2.17 on 2026-09-23 12:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_botclientprofile_db_on_delete"),
        ("orders", "0044_order_rail_station"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppBotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("allowed_chat_ids", models.JSONField(blank=True, default=list)),
                ("allowed_sender_ids", models.JSONField(blank=True, default=list)),
                ("show_amounts_in_reply", models.BooleanField(default=False)),
                ("duplicate_window_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "price_tolerance_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15"), max_digits=5
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "runtime_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "runtime_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instance_state",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("instance_state_at", models.DateTimeField(blank=True, null=True)),
                ("seen_chats", models.JSONField(blank=True, default=dict)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="green_api", max_length=20)),
                ("provider_message_id", models.CharField(max_length=160)),
                ("chat_id", models.CharField(max_length=128)),
                ("chat_name", models.CharField(blank=True, default="", max_length=200)),
                ("sender_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("message", "Сообщение"),
                            ("edited", "Изменено"),
                            ("deleted", "Удалено"),
                        ],
                        default="message",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("parsed", "Разобрано"),
                            ("applied", "Проведено"),
                            ("needs_review", "На проверке"),
                            ("awaiting_confirmation", "Черновик на проверке"),
                            ("rejected", "Отклонено"),
                            ("ignored", "Пропущено"),
                            ("failed", "Ошибка"),
                        ],
                        default="received",
                        max_length=24,
                    ),
                ),
                ("parsed", models.JSONField(blank=True, default=dict)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("draft", models.TextField(blank=True, default="")),
                ("reply", models.TextField(blank=True, default="")),
                (
                    "reply_message_id",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("reply_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reply_attempts", models.PositiveSmallIntegerField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_messages",
                        to="orders.order",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="bots.botmessage",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "-received_at"],
                        name="bots_message_status_idx",
                    ),
                    models.Index(
                        fields=["chat_id", "provider_message_id"],
                        name="bots_message_chat_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_message_id"),
                        name="bots_message_provider_id_unique",
                    )
                ],
            },
        ),
    ]
