# Generated by Django 5.2.17 on 2026-09-23 13:52

from django.db import migrations, models

OLD_DEFAULT = 14
NEW_DEFAULT = 3


def forwards(apps, schema_editor):
    """Окно дублей теперь «±дней от даты отчёта»: строка со старым значением
    по умолчанию (14 — «любой повтор за две недели», отклонено владельцем)
    переходит на 3. Строки может и не быть — тогда её создаст ``load()`` с 3."""
    settings_model = apps.get_model("bots", "WhatsAppBotSettings")
    settings_model.objects.filter(duplicate_window_days=OLD_DEFAULT).update(duplicate_window_days=NEW_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_whatsapp_bot_db_on_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappbotsettings",
            name="duplicate_window_days",
            field=models.PositiveSmallIntegerField(default=NEW_DEFAULT),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
