# Generated by Django 5.2.17 on 2026-09-24 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0005_whatsapp_bot_duplicate_window_3_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappbotsettings",
            name="report_recipient_name",
            field=models.CharField(
                db_default="Динара", default="Динара", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="whatsappbotsettings",
            name="report_recipient_phone",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=15
            ),
        ),
        migrations.CreateModel(
            name="OutgoingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("recipient_name", models.CharField(max_length=60)),
                ("phone", models.CharField(blank=True, default="", max_length=15)),
                ("chat_id", models.CharField(blank=True, default="", max_length=128)),
                ("text", models.TextField()),
                ("order_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("sent", "Отправлено"),
                            ("failed", "Не отправлено"),
                            ("link", "Ссылкой WhatsApp"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "id"], name="bots_outgoing_status_idx"
                    )
                ],
            },
        ),
    ]
