# Generated by Django 5.2.17 on 2026-09-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0007_outgoing_report_db_on_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoingmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "В очереди"),
                    ("sending", "Отправляется"),
                    ("sent", "Отправлено"),
                    ("failed", "Не отправлено"),
                    ("unknown", "Не подтверждено"),
                    ("link", "Ссылкой WhatsApp"),
                ],
                max_length=10,
            ),
        ),
    ]
