# Generated by Django 5.2.17 on 2026-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_outgoing_report_sending_unknown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Получено"),
                    ("applied", "Проведено"),
                    ("needs_review", "На проверке"),
                    ("awaiting_confirmation", "Черновик на проверке"),
                    ("rejected", "Отклонено"),
                    ("ignored", "Пропущено"),
                    ("failed", "Ошибка"),
                ],
                default="received",
                max_length=24,
            ),
        ),
    ]
