# Generated by Django 5.2.15 on 2026-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("rbac", "0007_dept2_payment_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="rbac.permission"
            ),
        ),
    ]
