# Generated by Django 5.2.15 on 2026-07-28 08:55
"""Индексы журнала событий: таблица только растёт, читается «сверху» и по типу.

CONCURRENTLY, чтобы не блокировать запись в растущую таблицу.
"""

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("eventlog", "0002_eventlog_order"),
        ("orders", "0028_payment_payment_paid_at_desc_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="eventlog",
            index=models.Index(
                fields=["-created_at", "-id"], name="eventlog_recent_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="eventlog",
            index=models.Index(fields=["event_type"], name="eventlog_event_type_idx"),
        ),
    ]
