# Generated by Django 5.2.17 on 2026-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattachment",
            name="kind",
            field=models.CharField(max_length=10),
        ),
    ]
