# Generated by Django 5.2.17 on 2026-09-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_attachment_kind_no_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Expand/contract rollout, как orders 0045/0046: уведомления о задачах
        # никто не читал, модель уходит из состояния Django. Таблица остаётся,
        # пока в неё может писать образ автоотката, но без внешних ключей:
        # ORM про неё больше не знает, и ни удаление задачи или сотрудника,
        # ни очистка таблиц не должны упираться в её ссылки.
        migrations.AlterField(
            model_name="tasknotification",
            name="task",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="tasknotification",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="TaskNotification"),
            ],
            database_operations=[],
        ),
    ]
