# Generated by Django 5.2.15 on 2026-06-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
