# Generated by Django 5.2.15 on 2026-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_remove_client_contact_remove_client_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="requisites",
        ),
        migrations.AddField(
            model_name="client",
            name="bank",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Банк"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="bank_account",
            field=models.CharField(
                blank=True, default="", max_length=34, verbose_name="Расчётный счёт"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="iin",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="ИИН/БИН"
            ),
        ),
    ]
