# Generated by Django 5.2.15 on 2026-06-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_remove_client_requisites_client_bank_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, default="", max_length=300)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "payment_schedule_type",
                    models.CharField(default="none", max_length=20),
                ),
                ("payment_days", models.JSONField(blank=True, default=list)),
                ("contract_signed_at", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
