# Generated by Django 5.2.15 on 2026-08-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_move_names_to_user"),
        ("sales", "0002_department_move_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="sales.department",
            ),
        ),
    ]
