# Generated by Django 5.2.15 on 2026-07-14 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_camera_health"),
        ("orders", "0012_order_deleted_at_order_deleted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aicountingsession",
            name="cameras_one_open_ai_counting_session",
        ),
        migrations.RemoveField(
            model_name="aicountingsession",
            name="singleton",
        ),
        migrations.AddConstraint(
            model_name="aicountingsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["starting", "active"])),
                fields=("camera",),
                name="cameras_one_open_session_per_camera",
            ),
        ),
    ]
