# Generated by Django 5.2.15 on 2026-07-29 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0012_ai_session_started_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alwaysondailyanalytics",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="AlwaysOnCountArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(db_index=True, max_length=32)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("model_total", models.PositiveIntegerField(default=0)),
                ("model_per_color", models.JSONField(blank=True, default=dict)),
                ("adjustment", models.IntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("days", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="always_on_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
