# Generated by Django 5.2.15 on 2026-07-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0013_always_on_count_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="alwaysoncountarchive",
            name="day_rows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alwaysondailyanalytics",
            name="archive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_rows",
                to="cameras.alwaysoncountarchive",
            ),
        ),
    ]
