# Generated by Django 5.2.15 on 2026-08-16 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def bootstrap_current_day_runs(apps, schema_editor):
    """Preserve today's live color totals without importing old production."""

    daily_analytics = apps.get_model("cameras", "AlwaysOnDailyAnalytics")
    production_run = apps.get_model("cameras", "AlwaysOnProductionRun")
    database = schema_editor.connection.alias
    current_day = timezone.localdate()

    rows = daily_analytics.objects.using(database).filter(
        day=current_day,
        archived_at__isnull=True,
    )
    for row in rows.iterator():
        raw_per_color = row.model_per_color
        if not isinstance(raw_per_color, dict):
            continue

        per_color = {}
        for raw_color, raw_bags in raw_per_color.items():
            if not isinstance(raw_color, str) or isinstance(raw_bags, bool):
                continue
            color = raw_color.strip().lower()
            if not color or len(color) > 32:
                continue
            if isinstance(raw_bags, int):
                bags = raw_bags
            elif isinstance(raw_bags, str) and raw_bags.strip().isdigit():
                bags = int(raw_bags.strip())
            else:
                continue
            if bags <= 0:
                continue
            per_color[color] = per_color.get(color, 0) + bags

        timestamp = row.updated_at
        if timestamp is None:
            continue
        for color, bags in per_color.items():
            production_run.objects.using(database).create(
                camera=row.camera,
                business_day=row.day,
                color=color,
                started_at=timestamp,
                last_counted_at=timestamp,
                ended_at=timestamp,
                model_bags=bags,
                is_approximate=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0018_ai_session_conveyor_observation"),
        ("catalog", "0011_expand_product_weights"),
        ("warehouse", "0008_alter_stockmovement_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlwaysOnProductionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(db_index=True, max_length=32)),
                ("business_day", models.DateField(db_index=True)),
                ("color", models.CharField(max_length=32)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("last_counted_at", models.DateTimeField()),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("model_bags", models.PositiveIntegerField(default=0)),
                ("is_approximate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["camera", "-started_at"],
                        name="aon_run_camera_started_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("camera", "color"),
                        name="cameras_one_open_run_per_color",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlwaysOnStockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                ("business_day", models.DateField()),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("blocked", "Blocked"),
                            ("posted", "Posted"),
                            ("empty", "Empty"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("total_bags", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-business_day", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("camera", "business_day"),
                        name="cameras_one_stock_batch_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlwaysOnColorProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                ("color", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="always_on_color_mappings",
                        to="catalog.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="always_on_color_mapping_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["camera", "color"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("camera", "color"),
                        name="cameras_one_product_per_camera_color",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlwaysOnProductionCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                ("business_day", models.DateField(db_index=True)),
                ("color", models.CharField(max_length=32)),
                ("delta", models.IntegerField()),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="always_on_production_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["camera", "business_day", "color"],
                        name="aon_corr_camera_day_color_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlwaysOnStockPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=32)),
                ("detected_bags", models.PositiveIntegerField()),
                ("correction_bags", models.IntegerField(default=0)),
                ("posted_bags", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cameras.alwaysonstockbatch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.stockreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["color"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "color"),
                        name="cameras_one_stock_posting_per_color",
                    )
                ],
            },
        ),
        migrations.RunPython(
            bootstrap_current_day_runs,
            migrations.RunPython.noop,
        ),
    ]
