# Generated by Django 5.2.15 on 2026-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0020_always_on_event_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePlateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("vehicle_number", models.CharField(max_length=8)),
                ("camera", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=4)),
                ("detected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stationary_seconds",
                    models.DecimalField(decimal_places=3, max_digits=8),
                ),
                ("confirmation_votes", models.PositiveSmallIntegerField()),
                (
                    "detector_confidence",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("ocr_confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("payload_json", models.JSONField(default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["vehicle_number"], name="plate_vehicle_number_idx"
                    ),
                    models.Index(fields=["detected_at"], name="plate_detected_at_idx"),
                    models.Index(
                        fields=["camera", "-detected_at"],
                        name="plate_camera_detected_idx",
                    ),
                ],
            },
        ),
    ]
