# Generated by Django 5.2.15 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0021_vehicle_plate_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleplateevent",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                ],
                default="received",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicleplateevent",
            name="processing_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicleplateevent",
            name="processing_action",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="vehicleplateevent",
            name="processing_error",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="vehicleplateevent",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleplateevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
