# Generated by Django 5.2.17 on 2026-09-07 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0031_retire_monoblock_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingTransportCamera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conveyor_camera", models.CharField(max_length=32, unique=True)),
                ("number_camera", models.CharField(max_length=32, unique=True)),
                (
                    "recognition_model",
                    models.CharField(
                        choices=[
                            ("vehicle_number", "Госномера грузовиков"),
                            ("wagon_number", "Номера вагонов"),
                        ],
                        max_length=32,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_transport_camera_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("conveyor_camera", models.F("number_camera")),
                            _negated=True,
                        ),
                        name="shipping_number_camera_separate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "recognition_model__in",
                                ["vehicle_number", "wagon_number"],
                            )
                        ),
                        name="shipping_number_model_valid",
                    ),
                ],
            },
        ),
    ]
