# Generated by Django 5.2.17 on 2026-09-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cameras", "0032_shipping_transport_camera"),
        ("orders", "0034_multi_warehouse_stock_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicountingsession",
            name="automatically_started",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ShippingTransportRecognitionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conveyor_camera", models.CharField(max_length=32)),
                ("number_camera", models.CharField(max_length=32)),
                ("recognition_model", models.CharField(max_length=32)),
                ("number", models.CharField(max_length=32)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("status", models.CharField(max_length=32)),
                (
                    "image",
                    models.FileField(
                        blank=True, upload_to="shipping-transport/%Y/%m/%d"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_recognitions",
                        to="orders.order",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_recognitions",
                        to="cameras.aicountingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ShippingTransportState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conveyor_camera", models.CharField(max_length=32, unique=True)),
                ("configuration_updated_at", models.DateTimeField()),
                ("state", models.CharField(default="waiting_number", max_length=32)),
                ("detail", models.CharField(blank=True, default="", max_length=500)),
                ("number", models.CharField(blank=True, default="", max_length=32)),
                (
                    "candidate_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("confirmations", models.PositiveSmallIntegerField(default=0)),
                ("candidate_since", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("frame_ids", models.JSONField(blank=True, default=list)),
                ("polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "binding",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation",
                        to="cameras.shippingtransportcamera",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_states",
                        to="cameras.shippingtransportrecognitionevent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_states",
                        to="cameras.aicountingsession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="shippingtransportrecognitionevent",
            index=models.Index(
                fields=["conveyor_camera", "-first_seen_at"],
                name="shipping_transport_seen_idx",
            ),
        ),
    ]
