# Generated by Django 5.2.17 on 2026-09-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0033_shipping_transport_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingtransportrecognitionevent",
            name="tracking",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="shippingtransportrecognitionevent",
            name="visit_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="shippingtransportstate",
            name="candidate_visit_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="shippingtransportstate",
            name="claimed_visit_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="shippingtransportstate",
            name="departure_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingtransportstate",
            name="tracking",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="shippingtransportstate",
            name="tracking_alert",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
