# Generated by Django 5.2.17 on 2026-09-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0034_shipping_transport_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingtransportcamera",
            name="loading_zone",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="shippingtransportstate",
            name="auto_finish",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
