# Generated by Django 5.2.17 on 2026-09-09 12:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def activate_future_sessions(apps, schema_editor):
    Settings = apps.get_model("cameras", "ShippingSessionSettings")
    alias = schema_editor.connection.alias
    policy, _ = Settings.objects.using(alias).get_or_create(
        singleton=True, defaults={"activated_at": django.utils.timezone.now()}
    )
    Cursor = apps.get_model("cameras", "AlwaysOnCounterCursor")
    Projection = apps.get_model("cameras", "ShippingLoadingCursor")
    # Skip already imported predeployment pages immediately, so new live counts
    # never wait behind a large historical scan and miss their photo deadline.
    Event = apps.get_model("cameras", "AlwaysOnImportedEvent")
    first_new = dict(Event.objects.using(alias).filter(
        occurred_at__gte=policy.activated_at,
    ).values("camera").annotate(first=models.Min("upstream_event_id")).values_list("camera", "first"))
    Projection.objects.using(alias).bulk_create([
        Projection(
            camera=row.camera,
            last_event_id=min(row.last_event_id or 0, first_new.get(row.camera, (row.last_event_id or 0)+1)-1),
            activated_at=policy.activated_at,
        )
        for row in Cursor.objects.using(alias).all().iterator()
    ], ignore_conflicts=True, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0035_shipping_automatic_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingLoadingCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(max_length=32, unique=True)),
                ("last_event_id", models.PositiveBigIntegerField(default=0)),
                ("activated_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingLoadingSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                (
                    "number_camera",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "configured_recognition_model",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "recognition_model",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("number", models.CharField(blank=True, default="", max_length=32)),
                (
                    "number_source",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("identity_status", models.CharField(default="pending", max_length=16)),
                (
                    "photo",
                    models.FileField(blank=True, upload_to="shipping-loading/%Y/%m/%d"),
                ),
                ("photo_taken_at", models.DateTimeField(blank=True, null=True)),
                ("photo_attempted", models.BooleanField(default=False)),
                ("primary_attempted", models.BooleanField(default=False)),
                ("identity_attempts", models.PositiveSmallIntegerField(default=0)),
                ("identity_lease_until", models.DateTimeField(blank=True, null=True)),
                (
                    "identity_next_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "identity_error",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "identity_response_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("started_at", models.DateTimeField()),
                ("last_counted_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_bags", models.PositiveBigIntegerField(default=0)),
                ("idle_timeout_seconds", models.PositiveIntegerField(default=300)),
                ("first_upstream_event_id", models.PositiveBigIntegerField()),
                ("last_upstream_event_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "first_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_loading_segments",
                        to="cameras.alwaysonimportedevent",
                    ),
                ),
                (
                    "last_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_loading_segments",
                        to="cameras.alwaysonimportedevent",
                    ),
                ),
            ],
            options={
                "ordering": ["camera", "first_upstream_event_id", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ShippingLoadingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_loading_event",
                        to="cameras.alwaysonimportedevent",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_events",
                        to="cameras.shippingloadingsegment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingLoadingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(db_index=True, max_length=32)),
                (
                    "recognition_model",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("number", models.CharField(blank=True, default="", max_length=32)),
                ("status", models.CharField(default="active", max_length=12)),
                ("total_bags", models.PositiveBigIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("last_counted_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_sessions",
                        to="cameras.shippingloadingsession",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_loading_sessions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="shippingloadingsegment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments",
                to="cameras.shippingloadingsession",
            ),
        ),
        migrations.CreateModel(
            name="ShippingSessionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "idle_timeout_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("idle_timeout_seconds__gte", 30),
                            ("idle_timeout_seconds__lte", 86400),
                        ),
                        name="shipping_idle_timeout_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("singleton", True)),
                        name="shipping_settings_singleton_true",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="shippingloadingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "closed", "merged"])),
                name="shipping_loading_session_status",
            ),
        ),
        migrations.AddIndex(
            model_name="shippingloadingsegment",
            index=models.Index(
                fields=["camera", "first_upstream_event_id"],
                name="ship_segment_camera_event_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingloadingsegment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("camera",),
                name="shipping_one_active_segment",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingloadingsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "identity_status__in",
                        ["pending", "processing", "identified", "unidentified"],
                    )
                ),
                name="shipping_segment_identity_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingloadingsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("idle_timeout_seconds__gte", 30),
                    ("idle_timeout_seconds__lte", 86400),
                ),
                name="shipping_segment_idle_range",
            ),
        ),
        migrations.RunPython(activate_future_sessions, migrations.RunPython.noop),
    ]
