# Generated by Django 5.2.17 on 2026-09-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def _unknown(field: str) -> Q:
    # Mirrors event_protocol.event_color_key: "unknown" or "unknown_<size>".
    return Q(**{f"{field}__iexact": "unknown"}) | Q(
        **{f"{field}__istartswith": "unknown_"}
    )


def mark_unknown_bags(apps, schema_editor):
    """Flag already imported AI 24/7 bags the camera left without an answer.

    Only the marker is set: decisions are taken by the resolver passes, and a
    posted shift is never touched by them. Old image rows keep ``""``.
    """

    Event = apps.get_model("cameras", "AlwaysOnImportedEvent")
    alias = schema_editor.connection.alias
    events = Event.objects.using(alias).filter(
        analytics_scope="ai_247",
        applied_to_analytics=True,
    )
    events.filter(
        _unknown("color") | (Q(color__isnull=True) & _unknown("class_name")),
        color_resolution="",
    ).update(color_resolution="unresolved")
    events.filter(_unknown("brand"), brand_resolution="").exclude(
        classification_status="white_reverse"
    ).update(brand_resolution="unresolved")


class Migration(migrations.Migration):
    dependencies = [
        ("cameras", "0036_shipping_count_sessions"),
        ("catalog", "0012_product_photo"),
        ("warehouse", "0010_multi_warehouse_stock_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alwaysonstockposting",
            options={"ordering": ["color", "id"]},
        ),
        migrations.AddField(
            model_name="alwaysonimportedevent",
            name="brand_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Classified by camera"),
                    ("unresolved", "Unresolved"),
                    ("neighbors", "Neighbours"),
                    ("votes", "Partial votes"),
                    ("manual", "Manual"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alwaysonimportedevent",
            name="color_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Classified by camera"),
                    ("unresolved", "Unresolved"),
                    ("neighbors", "Neighbours"),
                    ("votes", "Partial votes"),
                    ("manual", "Manual"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alwaysonimportedevent",
            name="resolution_note",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="alwaysonimportedevent",
            name="resolved_brand",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="alwaysonimportedevent",
            name="resolved_color",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="alwaysonimportedevent",
            name="verification_votes",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="alwaysonstockbatch",
            name="pending_bags",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="alwaysonstockposting",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="always_on_stock_postings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alwaysonstockposting",
            name="kind",
            field=models.CharField(
                choices=[
                    ("shift", "Shift posting"),
                    ("manual_color", "Manual colour assignment"),
                ],
                db_default="shift",
                default="shift",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alwaysonstockposting",
            name="resolved_bags",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddIndex(
            model_name="alwaysonimportedevent",
            index=models.Index(
                condition=models.Q(
                    models.Q(("color_resolution", ""), _negated=True),
                    models.Q(("brand_resolution", ""), _negated=True),
                    _connector="OR",
                ),
                fields=["camera", "occurred_at"],
                name="aon_event_resolution_idx",
            ),
        ),
        # Add the narrower guarantee before dropping the old one so a shift
        # is never without its one-posting-per-colour fence.
        migrations.AddConstraint(
            model_name="alwaysonstockposting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "shift")),
                fields=("batch", "color"),
                name="cameras_one_shift_posting_per_color",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="alwaysonstockposting",
            name="cameras_one_stock_posting_per_color",
        ),
        migrations.RunPython(mark_unknown_bags, migrations.RunPython.noop),
    ]
