# Generated by Django 5.2.17 on 2026-09-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0037_ai247_unknown_color_resolution"),
    ]

    operations = [
        # Expand/contract rollout, как tasks 0003: автозахват заказа по номеру
        # удалён, модели уходят из состояния Django. Таблицы остаются для
        # образа автоотката, но без внешних ключей наружу: ORM про них больше
        # не знает, и ни удаление заказа, сессии подсчёта или камеры номера,
        # ни очистка таблиц не должны упираться в их ссылки.
        migrations.AlterField(
            model_name="shippingtransportstate",
            name="binding",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation",
                to="cameras.shippingtransportcamera",
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransportstate",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transport_states",
                to="cameras.aicountingsession",
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransportrecognitionevent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transport_recognitions",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransportrecognitionevent",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transport_recognitions",
                to="cameras.aicountingsession",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="ShippingTransportState"),
                migrations.DeleteModel(name="ShippingTransportRecognitionEvent"),
            ],
            database_operations=[],
        ),
    ]
