# Generated by Django 5.2.17 on 2026-09-24 10:48

from django.db import migrations, models

from apps.common.migration_ops import db_on_delete


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0038_remove_shipping_transport_automation"),
    ]

    operations = [
        # Expand/contract rollout, как orders 0046: поля уходят из состояния
        # Django, колонки остаются для образа автоотката. NOT NULL колонкам
        # сначала нужен db_default — новый код их в INSERT не передаёт.
        migrations.AlterField(
            model_name="alwaysoncountercursor",
            name="last_mode",
            field=models.CharField(blank=True, db_default="", default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="shippingloadingsegment",
            name="last_upstream_event_id",
            field=models.PositiveBigIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="shippingloadingsegment",
            name="last_event",
            field=models.ForeignKey(
                null=True,
                on_delete=models.PROTECT,
                related_name="last_loading_segments",
                to="cameras.alwaysonimportedevent",
            ),
        ),
        # Ключ остаётся в базе: удаление события обнуляет его сама база,
        # ORM про поле больше не знает.
        db_on_delete("cameras", "ShippingLoadingSegment", "last_event", "SET NULL"),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="alwaysoncountercursor", name="last_mode"),
                migrations.RemoveField(model_name="camerahealthstate", name="last_changed_at"),
                migrations.RemoveField(model_name="shippingloadingsegment", name="last_event"),
                migrations.RemoveField(
                    model_name="shippingloadingsegment",
                    name="last_upstream_event_id",
                ),
            ],
            database_operations=[],
        ),
    ]
