# Generated by Django 5.2.17 on 2026-09-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0043_remove_shipping_bootstrap_scope_confirmed"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vehicleplateevent",
            name="plate_vehicle_number_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicleplateevent",
            name="plate_detected_at_idx",
        ),
    ]
