# Generated by Django 5.2.17 on 2026-09-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0044_remove_plate_event_list_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingTrainMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(max_length=32)),
                ("started_at", models.DateTimeField()),
                ("stopped_at", models.DateTimeField()),
                ("seconds", models.FloatField()),
                ("high_seconds", models.FloatField()),
                ("mean_fraction", models.FloatField()),
                ("interrupted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["camera", "stopped_at"],
                "indexes": [
                    models.Index(
                        fields=["camera", "stopped_at"], name="ship_train_move_stop_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("camera", "started_at"),
                        name="shipping_train_move_unique_start",
                    )
                ],
            },
        ),
    ]
