# Generated by Django 5.2.17 on 2026-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0045_shipping_train_move"),
    ]

    operations = [
        migrations.AddField(
            model_name="alwaysoncountercursor",
            name="event_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
