# Generated by Django 5.2.17 on 2026-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0046_cursor_event_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="alwaysondailyanalytics",
            name="adjustment_per_color",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="shippingdailyanalytics",
            name="adjustment_per_color",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="shippingloadingsession",
            name="colors_adjustment",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
    ]
