# Generated by Django 5.2.15 on 2026-06-22 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_arrival_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("camera_id", models.CharField(max_length=60, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("entry", "Въезд"),
                            ("counter", "Счётчик загрузки"),
                            ("exit", "Выезд"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(max_length=80)),
                ("response_template", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(blank=True, default="", max_length=30)),
                ("payload_bags", models.IntegerField(blank=True, null=True)),
                (
                    "payload_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("decision", models.CharField(max_length=10)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="webhooks.camera",
                    ),
                ),
                (
                    "matched_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_calls",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
