# Generated by Django 5.2.15 on 2026-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="status",
            field=models.CharField(
                choices=[("pending", "Обнаружена"), ("active", "Активна")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Въезд"),
                    ("counter", "Счётчик загрузки"),
                    ("exit", "Выезд"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
