# Generated by Django 5.2.15 on 2026-06-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_videojob"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CountSession",
        ),
    ]
