# Generated by Django 5.2.15 on 2026-06-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='net_weight_kg',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weigh_out_kg',
        ),
    ]
