# Generated by Django 5.2.15 on 2026-06-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_remove_shipment_net_weight_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="loading_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="truck_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
