# Generated by Django 5.2.17 on 2026-09-16 14:45

import apps.shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0006_remove_shipment_scale_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaybillSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "point_name",
                    models.CharField(default="мельница Аксу", max_length=120),
                ),
                (
                    "signers",
                    models.JSONField(
                        default=apps.shipments.models.default_waybill_signers
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
