# Generated by Django 5.2.17 on 2026-09-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_productalias"),
        ("shipments", "0007_waybill_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentWagon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=8)),
                (
                    "product_label_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "product_weight_kg_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("bags", models.PositiveIntegerField()),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_wagons",
                        to="catalog.product",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wagons",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(fields=["number"], name="shipment_wagon_number_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipment", "number"),
                        name="shipment_wagon_unique_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number__regex", "^[0-9]{8}$")),
                        name="shipment_wagon_number_digits",
                    ),
                ],
            },
        ),
    ]
