# Generated by Django 5.2.17 on 2026-09-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_whatsapp_bot_db_on_delete"),
        ("shipments", "0009_shipmentwagon_db_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentwagon",
            name="source_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wagons",
                to="bots.botmessage",
            ),
        ),
    ]
