# Generated by Django 5.2.17 on 2026-09-24 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_outgoing_report"),
        ("shipments", "0010_shipmentwagon_source_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="report_message",
            field=models.ForeignKey(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="bots.outgoingmessage",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="report_sent_at",
            field=models.DateTimeField(blank=True, db_default=None, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="report_sent_by",
            field=models.ForeignKey(
                blank=True,
                db_default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
