# Generated by Django 5.2.17 on 2026-09-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_department_move_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="apipay_api_key_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="department",
            name="apipay_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="apipay_webhook_secret_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
